### ISSUE TITLE
Firebase auth issue

### ISSUE THREAD

**Issue by itjustwerks** [webstylestory/figolia#21]
I have figolia running with the forever script, and sometimes it gets hung up (changes to Firebase aren't reflected in Algolia). If I tail the forever log on the server, I see something like this:

```
...
data:    /opt/bitnami/nodejs/bin/figolia:18443 - Fri, 02 Jun 2017 21:40:28 GMT figolia:info:add-to-index Pushing 2 object(s) to index prod_products
data:    /opt/bitnami/nodejs/bin/figolia:18443 - Fri, 02 Jun 2017 21:40:28 GMT figolia:info:add-to-index Pushing 2 object(s) to index prod_products
data:    /opt/bitnami/nodejs/bin/figolia:18443 - Fri, 02 Jun 2017 21:40:28 GMT figolia:info:add-to-index Pushing 2 object(s) to index prod_products
data:    /opt/bitnami/nodejs/bin/figolia:18443 - Fri, 02 Jun 2017 21:40:28 GMT figolia:info:add-to-index Pushing 2 object(s) to index prod_products
data:    /opt/bitnami/nodejs/bin/figolia:18443 - Fri, 02 Jun 2017 21:40:28 GMT figolia:info:add-to-index Pushing 2 object(s) to index prod_products
data:    /opt/bitnami/nodejs/bin/figolia:18443 - Fri, 02 Jun 2017 21:40:28 GMT figolia:info:add-to-index Pushing 2 object(s) to index prod_products
data:    /opt/bitnami/nodejs/bin/figolia:18443 - FIREBASE WARNING: auth() was canceled: Auth token is expired. 
```

Can anyone tell me why this is happening? If I restart figolia, it begins working again for a little while. The "firebase/secret" node in defaults.conf.js specified a "Database Secret" from the Firebase Service Accounts tab, which are now deprecated. I'm assuming it has something to do with that? Is there a way to update figolia to use the new Firebase Admin SDK?

**Comment by pandaiolo** [comment]
Thanks for raising that issue, i'll have a look probably tomorrow

**Comment by pandaiolo** [comment]
I guess I have to update to `firebase-admin`. `v5` was just released, I'll try to update the codebase this week end.

**Comment by pandaiolo** [comment]
I updated `figolia` on `npm`, you should upgrade to `v0.4.6`. Let me know if it fixes your authentication issues. Upgrade info to version 0.4.x also added to the docs. Here is a copy and paste:

#### Update from v0.3.x to v0.4.x

`firebase` package is now deprecated on the server, hence the update to use `firebase-admin`. You have to update your figolia configuration to remove the `firebase.secret` entry, and replace it with a `firebase.serviceAccountFile` pointing to your firebase key json file. It can be downloaded from the Firebase Console in the last tabs of the settings of your project. NEVER SHARE THAT FILE.

Basic steps (for a global install):

  1. `npm i -g figolia@^0.4.x`
  2. Download the service account json file from your Firebase console
  3. In your figolia configuration file, replace `secret` by `serviceAccountFile` which value is the path to the file you just downloaded
  4. If you store the service account file in a project with versioned source code, do not commit it (for example by adding a line in you `.gitignore` file)
  5. Restart your `figolia` services, and you're done!
  6. Report any issues ;-)

**Comment by itjustwerks** [comment]
@pandaiolo, thank you so much for resolving this! I completed the update this morning and it's been up all day. Internet high five to you sir.
